// Generated by the Jungle material-tactic miner
// (scripts/variant-lab/jungle-material-miner.ts). Do not hand-edit; re-run the
// miner and paste its `--emit-module` output here.
//
// Material tactics: the solver forces a decisive material gain (a captured piece)
// with the game still in progress. Found by a pure-material minimax with
// quiescence, so the gain is exact; `centipawns` = the guaranteed value won.
//
// The local structural type mirrors `JunglePuzzle` in puzzles-jungle.ts so the
// array is assignable when spread there, while keeping this file free of a
// circular import.

import type { JUNGLE_SPEC_ID } from './game-specs.js';
import type { JungleColor, JungleGameState, JungleMove } from './variants-jungle.js';

type MaterialJunglePuzzleTheme =
  | 'trap'
  | 'water-leap'
  | 'rank-up'
  | 'rat'
  | 'elephant'
  | 'lion'
  | 'tiger'
  | 'winning';

type MaterialJunglePuzzle = {
  id: string;
  variant: typeof JUNGLE_SPEC_ID;
  title: string;
  initial: JungleGameState;
  solution: JungleMove[];
  goal: { type: 'winning-advantage'; winner?: JungleColor; centipawns?: number };
  themes: MaterialJunglePuzzleTheme[];
};

export const MATERIAL_JUNGLE_PUZZLES: readonly MaterialJunglePuzzle[] = [
  {
    id: 'jungle-material-001',
    variant: 'jungle',
    title: 'Black Cat wins material (+65)',
    initial: {
      id: 'jungle-material-001',
      board: {
        a9: {
          color: 'black',
          role: 'tiger',
        },
        a6: {
          color: 'red',
          role: 'rat',
        },
        a2: {
          color: 'red',
          role: 'lion',
        },
        f2: {
          color: 'red',
          role: 'tiger',
        },
        b1: {
          color: 'red',
          role: 'dog',
        },
        b3: {
          color: 'red',
          role: 'leopard',
        },
        e7: {
          color: 'black',
          role: 'leopard',
        },
        g1: {
          color: 'red',
          role: 'cat',
        },
        g8: {
          color: 'black',
          role: 'dog',
        },
        d2: {
          color: 'red',
          role: 'wolf',
        },
        b8: {
          color: 'black',
          role: 'wolf',
        },
        e6: {
          color: 'black',
          role: 'rat',
        },
        g5: {
          color: 'red',
          role: 'elephant',
        },
        a7: {
          color: 'black',
          role: 'cat',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 28,
      progressClock: 0,
      positionCounts: {
        'black|.D....CL..W.T..P..................ER...r..c...p...w....dt......': 1,
      },
    },
    solution: [
      {
        from: 'a7',
        to: 'a6',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 65,
    },
    themes: ['winning', 'rank-up'],
  },
  {
    id: 'jungle-material-002',
    variant: 'jungle',
    title: 'Black Rat wins material (+100)',
    initial: {
      id: 'jungle-material-002',
      board: {
        a6: {
          color: 'black',
          role: 'cat',
        },
        f2: {
          color: 'red',
          role: 'tiger',
        },
        g1: {
          color: 'red',
          role: 'cat',
        },
        g8: {
          color: 'black',
          role: 'dog',
        },
        g5: {
          color: 'red',
          role: 'elephant',
        },
        b8: {
          color: 'black',
          role: 'wolf',
        },
        a1: {
          color: 'red',
          role: 'lion',
        },
        d7: {
          color: 'black',
          role: 'leopard',
        },
        a3: {
          color: 'red',
          role: 'leopard',
        },
        a8: {
          color: 'black',
          role: 'tiger',
        },
        b2: {
          color: 'red',
          role: 'dog',
        },
        g6: {
          color: 'black',
          role: 'rat',
        },
        d2: {
          color: 'red',
          role: 'wolf',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 35,
      progressClock: 11,
      positionCounts: {
        'black|L.....C.D.W.T.P...................Ec.....r...p...tw....d.......': 1,
      },
    },
    solution: [
      {
        from: 'g6',
        to: 'g5',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 100,
    },
    themes: ['winning', 'rat', 'rank-up'],
  },
  {
    id: 'jungle-material-003',
    variant: 'jungle',
    title: 'Red Tiger wins material (+40)',
    initial: {
      id: 'jungle-material-003',
      board: {
        g8: {
          color: 'black',
          role: 'dog',
        },
        g5: {
          color: 'black',
          role: 'rat',
        },
        a1: {
          color: 'red',
          role: 'lion',
        },
        a3: {
          color: 'red',
          role: 'leopard',
        },
        f1: {
          color: 'red',
          role: 'cat',
        },
        a2: {
          color: 'red',
          role: 'dog',
        },
        b8: {
          color: 'black',
          role: 'tiger',
        },
        a5: {
          color: 'black',
          role: 'cat',
        },
        e3: {
          color: 'red',
          role: 'wolf',
        },
        f8: {
          color: 'black',
          role: 'wolf',
        },
        f7: {
          color: 'red',
          role: 'tiger',
        },
        d5: {
          color: 'black',
          role: 'leopard',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 46,
      progressClock: 14,
      positionCounts: {
        'red|L....C.D......P...W.........c..p..r............T..t...wd.......': 1,
      },
    },
    solution: [
      {
        from: 'f7',
        to: 'f8',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 40,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-004',
    variant: 'jungle',
    title: 'Red Leopard wins material (+40)',
    initial: {
      id: 'jungle-material-004',
      board: {
        d4: {
          color: 'red',
          role: 'leopard',
        },
        e1: {
          color: 'red',
          role: 'tiger',
        },
        f1: {
          color: 'red',
          role: 'wolf',
        },
        e4: {
          color: 'black',
          role: 'rat',
        },
        d2: {
          color: 'red',
          role: 'lion',
        },
        e8: {
          color: 'black',
          role: 'leopard',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        f8: {
          color: 'black',
          role: 'lion',
        },
        g5: {
          color: 'black',
          role: 'dog',
        },
        c7: {
          color: 'black',
          role: 'cat',
        },
        a5: {
          color: 'black',
          role: 'tiger',
        },
        c3: {
          color: 'red',
          role: 'dog',
        },
        d5: {
          color: 'black',
          role: 'wolf',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 65,
      progressClock: 6,
      positionCounts: {
        'red|....TW....L.E...D.......Pr..t..w..d.........c........pl........': 1,
      },
    },
    solution: [
      {
        from: 'd4',
        to: 'd5',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 40,
    },
    themes: ['winning', 'rank-up'],
  },
  {
    id: 'jungle-material-005',
    variant: 'jungle',
    title: 'Black Lion wins material (+40)',
    initial: {
      id: 'jungle-material-005',
      board: {
        g2: {
          color: 'red',
          role: 'cat',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
        c6: {
          color: 'red',
          role: 'rat',
        },
        c8: {
          color: 'black',
          role: 'cat',
        },
        c7: {
          color: 'black',
          role: 'wolf',
        },
        b7: {
          color: 'black',
          role: 'tiger',
        },
        f9: {
          color: 'black',
          role: 'rat',
        },
        b2: {
          color: 'red',
          role: 'leopard',
        },
        c1: {
          color: 'red',
          role: 'dog',
        },
        f7: {
          color: 'black',
          role: 'lion',
        },
        f1: {
          color: 'red',
          role: 'tiger',
        },
        b1: {
          color: 'red',
          role: 'lion',
        },
        a9: {
          color: 'black',
          role: 'elephant',
        },
        g5: {
          color: 'red',
          role: 'elephant',
        },
        f8: {
          color: 'black',
          role: 'leopard',
        },
        f3: {
          color: 'red',
          role: 'wolf',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 41,
      progressClock: 81,
      positionCounts: {
        'black|.LD..T..P....C.....W..............E..R.....tw..l...c..p.e...dr.': 1,
      },
    },
    solution: [
      {
        from: 'f7',
        to: 'f3',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 40,
    },
    themes: ['winning', 'lion', 'water-leap', 'rank-up'],
  },
  {
    id: 'jungle-material-006',
    variant: 'jungle',
    title: 'Black Lion wins material (+75)',
    initial: {
      id: 'jungle-material-006',
      board: {
        g2: {
          color: 'red',
          role: 'cat',
        },
        c8: {
          color: 'black',
          role: 'cat',
        },
        c7: {
          color: 'black',
          role: 'wolf',
        },
        b7: {
          color: 'black',
          role: 'tiger',
        },
        f9: {
          color: 'black',
          role: 'rat',
        },
        b2: {
          color: 'red',
          role: 'leopard',
        },
        c1: {
          color: 'red',
          role: 'dog',
        },
        b1: {
          color: 'red',
          role: 'lion',
        },
        a9: {
          color: 'black',
          role: 'elephant',
        },
        g5: {
          color: 'red',
          role: 'elephant',
        },
        f8: {
          color: 'black',
          role: 'leopard',
        },
        f3: {
          color: 'black',
          role: 'lion',
        },
        e8: {
          color: 'black',
          role: 'dog',
        },
        d6: {
          color: 'red',
          role: 'rat',
        },
        f2: {
          color: 'red',
          role: 'tiger',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 43,
      progressClock: 1,
      positionCounts: {
        'black|.LD.....P...TC.....l..............E...R....tw......c.dp.e....r.': 1,
      },
    },
    solution: [
      {
        from: 'f3',
        to: 'f2',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 75,
    },
    themes: ['winning', 'lion', 'rank-up'],
  },
  {
    id: 'jungle-material-007',
    variant: 'jungle',
    title: 'Red Lion wins material (+90)',
    initial: {
      id: 'jungle-material-007',
      board: {
        g9: {
          color: 'black',
          role: 'dog',
        },
        g1: {
          color: 'red',
          role: 'wolf',
        },
        g2: {
          color: 'red',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'leopard',
        },
        d8: {
          color: 'black',
          role: 'rat',
        },
        c2: {
          color: 'red',
          role: 'lion',
        },
        g3: {
          color: 'red',
          role: 'tiger',
        },
        f7: {
          color: 'black',
          role: 'wolf',
        },
        c9: {
          color: 'black',
          role: 'tiger',
        },
        c8: {
          color: 'black',
          role: 'cat',
        },
        c3: {
          color: 'black',
          role: 'lion',
        },
        b2: {
          color: 'red',
          role: 'rat',
        },
        b9: {
          color: 'black',
          role: 'elephant',
        },
        f3: {
          color: 'red',
          role: 'leopard',
        },
        c1: {
          color: 'red',
          role: 'cat',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 48,
      progressClock: 0,
      positionCounts: {
        'red|..C...W.RL...E..l..PT..........................w...crp...et...d': 1,
      },
    },
    solution: [
      {
        from: 'c2',
        to: 'c3',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 90,
    },
    themes: ['winning', 'lion', 'rank-up'],
  },
  {
    id: 'jungle-material-008',
    variant: 'jungle',
    title: 'Red Rat wins material (+90)',
    initial: {
      id: 'jungle-material-008',
      board: {
        g9: {
          color: 'black',
          role: 'dog',
        },
        g1: {
          color: 'red',
          role: 'wolf',
        },
        g2: {
          color: 'red',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'leopard',
        },
        d8: {
          color: 'black',
          role: 'rat',
        },
        g3: {
          color: 'red',
          role: 'tiger',
        },
        c9: {
          color: 'black',
          role: 'tiger',
        },
        c8: {
          color: 'black',
          role: 'cat',
        },
        b9: {
          color: 'black',
          role: 'elephant',
        },
        c1: {
          color: 'black',
          role: 'lion',
        },
        f1: {
          color: 'red',
          role: 'leopard',
        },
        f8: {
          color: 'black',
          role: 'wolf',
        },
        b1: {
          color: 'red',
          role: 'rat',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 51,
      progressClock: 0,
      positionCounts: {
        'red|.Rl..PW......E......T..............................crpw..et...d': 1,
      },
    },
    solution: [
      {
        from: 'b1',
        to: 'c1',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 90,
    },
    themes: ['winning', 'rat', 'trap'],
  },
  {
    id: 'jungle-material-009',
    variant: 'jungle',
    title: 'Red Tiger wins material (+40)',
    initial: {
      id: 'jungle-material-009',
      board: {
        g1: {
          color: 'red',
          role: 'wolf',
        },
        d8: {
          color: 'black',
          role: 'rat',
        },
        c2: {
          color: 'black',
          role: 'lion',
        },
        a9: {
          color: 'black',
          role: 'elephant',
        },
        f7: {
          color: 'black',
          role: 'wolf',
        },
        f1: {
          color: 'red',
          role: 'leopard',
        },
        c8: {
          color: 'black',
          role: 'tiger',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        b7: {
          color: 'black',
          role: 'cat',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
        g7: {
          color: 'red',
          role: 'tiger',
        },
        e7: {
          color: 'black',
          role: 'leopard',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 64,
      progressClock: 24,
      positionCounts: {
        'red|.....PW..l..E..............................c..pwT..tr...e...d..': 1,
      },
    },
    solution: [
      {
        from: 'g7',
        to: 'f7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 40,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-010',
    variant: 'jungle',
    title: 'Red Tiger wins material (+50)',
    initial: {
      id: 'jungle-material-010',
      board: {
        g1: {
          color: 'red',
          role: 'wolf',
        },
        d8: {
          color: 'black',
          role: 'rat',
        },
        c2: {
          color: 'black',
          role: 'lion',
        },
        a9: {
          color: 'black',
          role: 'elephant',
        },
        f7: {
          color: 'red',
          role: 'tiger',
        },
        f1: {
          color: 'red',
          role: 'leopard',
        },
        c8: {
          color: 'black',
          role: 'tiger',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
        e7: {
          color: 'black',
          role: 'leopard',
        },
        a7: {
          color: 'black',
          role: 'cat',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 65,
      progressClock: 1,
      positionCounts: {
        'red|.....PW..l..E.............................c...pT...tr...e...d..': 1,
      },
    },
    solution: [
      {
        from: 'f7',
        to: 'e7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 50,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-011',
    variant: 'jungle',
    title: 'Red Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-011',
      board: {
        g1: {
          color: 'red',
          role: 'wolf',
        },
        d8: {
          color: 'black',
          role: 'rat',
        },
        a9: {
          color: 'black',
          role: 'elephant',
        },
        f7: {
          color: 'red',
          role: 'tiger',
        },
        f1: {
          color: 'red',
          role: 'leopard',
        },
        c8: {
          color: 'black',
          role: 'tiger',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
        e7: {
          color: 'black',
          role: 'leopard',
        },
        a7: {
          color: 'black',
          role: 'cat',
        },
        e2: {
          color: 'red',
          role: 'elephant',
        },
        d2: {
          color: 'black',
          role: 'lion',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 66,
      progressClock: 3,
      positionCounts: {
        'red|.....PW...lE..............................c...pT...tr...e...d..': 1,
      },
    },
    solution: [
      {
        from: 'e2',
        to: 'd2',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'trap'],
  },
  {
    id: 'jungle-material-012',
    variant: 'jungle',
    title: 'Red Lion wins material (+75)',
    initial: {
      id: 'jungle-material-012',
      board: {
        c9: {
          color: 'black',
          role: 'cat',
        },
        f3: {
          color: 'red',
          role: 'elephant',
        },
        e7: {
          color: 'black',
          role: 'leopard',
        },
        c3: {
          color: 'red',
          role: 'leopard',
        },
        g4: {
          color: 'red',
          role: 'cat',
        },
        c2: {
          color: 'red',
          role: 'dog',
        },
        f1: {
          color: 'red',
          role: 'wolf',
        },
        g9: {
          color: 'black',
          role: 'rat',
        },
        g3: {
          color: 'red',
          role: 'tiger',
        },
        a7: {
          color: 'black',
          role: 'tiger',
        },
        b4: {
          color: 'red',
          role: 'rat',
        },
        e8: {
          color: 'black',
          role: 'dog',
        },
        f8: {
          color: 'black',
          role: 'lion',
        },
        b9: {
          color: 'black',
          role: 'wolf',
        },
        a6: {
          color: 'red',
          role: 'lion',
        },
        d7: {
          color: 'black',
          role: 'elephant',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 24,
      progressClock: 46,
      positionCounts: {
        'red|.....W...D......P..ET.R....C.......L......t..ep......dl..wc...r': 1,
      },
    },
    solution: [
      {
        from: 'a6',
        to: 'a7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 75,
    },
    themes: ['winning', 'lion', 'rank-up'],
  },
  {
    id: 'jungle-material-013',
    variant: 'jungle',
    title: 'Red Lion wins material (+90)',
    initial: {
      id: 'jungle-material-013',
      board: {
        e7: {
          color: 'black',
          role: 'leopard',
        },
        f1: {
          color: 'red',
          role: 'wolf',
        },
        c9: {
          color: 'black',
          role: 'wolf',
        },
        b3: {
          color: 'red',
          role: 'leopard',
        },
        d7: {
          color: 'black',
          role: 'elephant',
        },
        d2: {
          color: 'red',
          role: 'dog',
        },
        a4: {
          color: 'red',
          role: 'rat',
        },
        g9: {
          color: 'black',
          role: 'rat',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        c7: {
          color: 'black',
          role: 'cat',
        },
        g2: {
          color: 'red',
          role: 'tiger',
        },
        d5: {
          color: 'black',
          role: 'lion',
        },
        d6: {
          color: 'red',
          role: 'lion',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 41,
      progressClock: 10,
      positionCounts: {
        'red|.....W....D.ET.P.....R.........l......L.....cep...........w.d.r': 1,
      },
    },
    solution: [
      {
        from: 'd6',
        to: 'd5',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 90,
    },
    themes: ['winning', 'lion', 'rank-up'],
  },
  {
    id: 'jungle-material-014',
    variant: 'jungle',
    title: 'Black Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-014',
      board: {
        e7: {
          color: 'black',
          role: 'leopard',
        },
        f1: {
          color: 'red',
          role: 'wolf',
        },
        c9: {
          color: 'black',
          role: 'wolf',
        },
        b3: {
          color: 'red',
          role: 'leopard',
        },
        a4: {
          color: 'red',
          role: 'rat',
        },
        g9: {
          color: 'black',
          role: 'rat',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
        c8: {
          color: 'black',
          role: 'cat',
        },
        d3: {
          color: 'red',
          role: 'dog',
        },
        g3: {
          color: 'red',
          role: 'tiger',
        },
        d7: {
          color: 'black',
          role: 'elephant',
        },
        d6: {
          color: 'red',
          role: 'lion',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 44,
      progressClock: 6,
      positionCounts: {
        'black|.....W......E..P.D..TR................L......ep....c......w.d.r': 1,
      },
    },
    solution: [
      {
        from: 'd7',
        to: 'd6',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'rank-up'],
  },
  {
    id: 'jungle-material-015',
    variant: 'jungle',
    title: 'Red Tiger wins material (+50)',
    initial: {
      id: 'jungle-material-015',
      board: {
        c9: {
          color: 'black',
          role: 'wolf',
        },
        a4: {
          color: 'red',
          role: 'rat',
        },
        g9: {
          color: 'black',
          role: 'rat',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
        d3: {
          color: 'red',
          role: 'dog',
        },
        b2: {
          color: 'red',
          role: 'leopard',
        },
        e2: {
          color: 'red',
          role: 'elephant',
        },
        f7: {
          color: 'black',
          role: 'leopard',
        },
        e1: {
          color: 'red',
          role: 'wolf',
        },
        a8: {
          color: 'black',
          role: 'cat',
        },
        f3: {
          color: 'red',
          role: 'tiger',
        },
        d5: {
          color: 'black',
          role: 'elephant',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 49,
      progressClock: 8,
      positionCounts: {
        'red|....W...P..E.....D.T.R.........e...............p.c........w.d.r': 1,
      },
    },
    solution: [
      {
        from: 'f3',
        to: 'f7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 50,
    },
    themes: ['winning', 'tiger', 'water-leap', 'rank-up'],
  },
  {
    id: 'jungle-material-016',
    variant: 'jungle',
    title: 'Black Tiger wins material (+75)',
    initial: {
      id: 'jungle-material-016',
      board: {
        e9: {
          color: 'black',
          role: 'lion',
        },
        c1: {
          color: 'red',
          role: 'dog',
        },
        g9: {
          color: 'black',
          role: 'leopard',
        },
        a7: {
          color: 'black',
          role: 'cat',
        },
        c4: {
          color: 'red',
          role: 'rat',
        },
        g7: {
          color: 'black',
          role: 'rat',
        },
        a3: {
          color: 'red',
          role: 'lion',
        },
        g2: {
          color: 'red',
          role: 'elephant',
        },
        d6: {
          color: 'black',
          role: 'wolf',
        },
        f2: {
          color: 'red',
          role: 'cat',
        },
        e1: {
          color: 'red',
          role: 'wolf',
        },
        b8: {
          color: 'black',
          role: 'elephant',
        },
        f7: {
          color: 'red',
          role: 'tiger',
        },
        f8: {
          color: 'black',
          role: 'tiger',
        },
        a1: {
          color: 'red',
          role: 'leopard',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 56,
      progressClock: 24,
      positionCounts: {
        'black|P.D.W.......CEL........R..............w...c....Tr.e...t.....l.p': 1,
      },
    },
    solution: [
      {
        from: 'f8',
        to: 'f7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 75,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-017',
    variant: 'jungle',
    title: 'Black Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-017',
      board: {
        c1: {
          color: 'red',
          role: 'dog',
        },
        g9: {
          color: 'black',
          role: 'leopard',
        },
        a7: {
          color: 'black',
          role: 'cat',
        },
        g7: {
          color: 'black',
          role: 'rat',
        },
        e1: {
          color: 'red',
          role: 'wolf',
        },
        f7: {
          color: 'black',
          role: 'tiger',
        },
        a1: {
          color: 'red',
          role: 'leopard',
        },
        c3: {
          color: 'red',
          role: 'rat',
        },
        c7: {
          color: 'black',
          role: 'wolf',
        },
        d2: {
          color: 'red',
          role: 'cat',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        b8: {
          color: 'black',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'lion',
        },
        b7: {
          color: 'red',
          role: 'lion',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 62,
      progressClock: 11,
      positionCounts: {
        'black|P.D.W.....C.E...R.........................cLw..tr.e..l........p': 1,
      },
    },
    solution: [
      {
        from: 'b8',
        to: 'b7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'rank-up'],
  },
  {
    id: 'jungle-material-018',
    variant: 'jungle',
    title: 'Red Lion wins material (+40)',
    initial: {
      id: 'jungle-material-018',
      board: {
        c1: {
          color: 'red',
          role: 'dog',
        },
        g9: {
          color: 'black',
          role: 'leopard',
        },
        g7: {
          color: 'black',
          role: 'rat',
        },
        e1: {
          color: 'red',
          role: 'wolf',
        },
        f7: {
          color: 'black',
          role: 'tiger',
        },
        a1: {
          color: 'red',
          role: 'leopard',
        },
        c3: {
          color: 'red',
          role: 'rat',
        },
        c7: {
          color: 'black',
          role: 'wolf',
        },
        d2: {
          color: 'red',
          role: 'cat',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        b8: {
          color: 'black',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'lion',
        },
        b7: {
          color: 'red',
          role: 'lion',
        },
        a6: {
          color: 'black',
          role: 'cat',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 63,
      progressClock: 12,
      positionCounts: {
        'red|P.D.W.....C.E...R..................c.......Lw..tr.e..l........p': 1,
      },
    },
    solution: [
      {
        from: 'b7',
        to: 'c7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 40,
    },
    themes: ['winning', 'lion', 'rank-up'],
  },
  {
    id: 'jungle-material-019',
    variant: 'jungle',
    title: 'Black Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-019',
      board: {
        c1: {
          color: 'red',
          role: 'dog',
        },
        g9: {
          color: 'black',
          role: 'leopard',
        },
        g7: {
          color: 'black',
          role: 'rat',
        },
        e1: {
          color: 'red',
          role: 'wolf',
        },
        f7: {
          color: 'black',
          role: 'tiger',
        },
        a1: {
          color: 'red',
          role: 'leopard',
        },
        c3: {
          color: 'red',
          role: 'rat',
        },
        c7: {
          color: 'red',
          role: 'lion',
        },
        d2: {
          color: 'red',
          role: 'cat',
        },
        e8: {
          color: 'black',
          role: 'lion',
        },
        a6: {
          color: 'black',
          role: 'cat',
        },
        e2: {
          color: 'red',
          role: 'elephant',
        },
        c8: {
          color: 'black',
          role: 'elephant',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 64,
      progressClock: 0,
      positionCounts: {
        'black|P.D.W.....CE....R..................c........L..tr..e.l........p': 1,
      },
    },
    solution: [
      {
        from: 'c8',
        to: 'c7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'rank-up'],
  },
  {
    id: 'jungle-material-020',
    variant: 'jungle',
    title: 'Red Leopard wins material (+40)',
    initial: {
      id: 'jungle-material-020',
      board: {
        g1: {
          color: 'red',
          role: 'tiger',
        },
        b3: {
          color: 'red',
          role: 'dog',
        },
        d8: {
          color: 'black',
          role: 'dog',
        },
        a8: {
          color: 'black',
          role: 'elephant',
        },
        d7: {
          color: 'black',
          role: 'leopard',
        },
        e3: {
          color: 'red',
          role: 'elephant',
        },
        e2: {
          color: 'red',
          role: 'wolf',
        },
        b8: {
          color: 'black',
          role: 'tiger',
        },
        d3: {
          color: 'red',
          role: 'leopard',
        },
        e7: {
          color: 'black',
          role: 'lion',
        },
        f7: {
          color: 'black',
          role: 'rat',
        },
        a3: {
          color: 'red',
          role: 'rat',
        },
        c9: {
          color: 'black',
          role: 'cat',
        },
        c1: {
          color: 'red',
          role: 'lion',
        },
        g3: {
          color: 'red',
          role: 'cat',
        },
        d4: {
          color: 'black',
          role: 'wolf',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 26,
      progressClock: 50,
      positionCounts: {
        'red|..L...T....W..RD.PE.C...w....................plr.et.d.....c....': 1,
      },
    },
    solution: [
      {
        from: 'd3',
        to: 'd4',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 40,
    },
    themes: ['winning', 'rank-up'],
  },
];
