// GENERATED by docs-private/luck-article/gen-figures.ts from the mined exhibit
// game bq_7e8ce2e7-8e64-4453-b9fd-9dcc4bd52fa9 (sweep + decision-vs-luck decomposition at analysis
// budget). Do not hand-edit; re-run the generator (see docs-private/luck-article/FINDINGS.md).

// Red-POV win% series of the exhibit game, downsampled for the /og/article
// share card: 'win' is the game as played, 'ghost' is the same game with every
// flip scored at its average tile (realized minus cumulative luck, clamped).
export const SKILL_VS_LUCK_OG_SERIES: { win: number[]; ghost: number[] } = {
  win: [
    50.6, 53, 53.6, 17.9, 20, 23.7, 32, 35.1, 43.8, 38.2, 32.2, 43.6, 52.3, 51.7, 54.8, 51.4, 40.5,
    42.9, 32.5, 29.9, 30.2, 43.5, 47.4, 48.3, 54.4, 54.1, 70.9, 64.5, 59.9, 55.9, 51.7, 41.3, 39.3,
    33.8, 24.6, 24.7, 44.6, 44.3, 42.7, 21.9, 19.9, 20.7, 19.7, 25.2, 21.9, 17.2, 16.7, 15.6, 16.6,
    14.7, 14.9, 14.1, 14.2, 13.9, 12.6, 15.4, 17.2, 16.8, 16.6, 16, 15.5, 15.6, 16.7, 14.1, 14.2,
    14, 12.6, 10.7, 10.5, 10.2, 9.6, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5,
  ],
  ghost: [
    50.6, 50.6, 55.6, 58.5, 58.3, 59.5, 63, 66, 72.9, 81.1, 85.9, 97.3, 100, 100, 100, 100, 100,
    100, 95.9, 93.3, 93.6, 94.7, 96.7, 97.5, 100, 100, 100, 100, 100, 100, 100, 100, 100, 98.1,
    88.9, 88.9, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
    100, 99.3, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 99.9, 98, 97.8, 97.5, 96.9,
    89.8, 89.8, 89.8, 89.8, 89.8, 89.8, 89.8, 89.8,
  ],
};
