// Entries for the landing News box and the /feed page.
//
// Workflow: when shipping a user-facing change, append a new entry with
// today's date. Newest first (both surfaces sort by date descending). Skip
// for internal-only changes (engine internals, infra, CI, refactors).
//
// STUDIES: do not post per published study, and never count them ("two new
// studies"): the count is wrong the next time one ships, and the homepage
// already lists them live from the API. Post when a WORK is finished (a manual,
// not a volume) or at a milestone worth a reader's attention. Individual
// publications reach people through the studies widget and /study on their own.

export type AnnouncementKind = 'status' | 'article' | 'release' | 'update';

export type Announcement = {
  date: string; // ISO YYYY-MM-DD
  kind: AnnouncementKind;
  headline: string;
  body?: string;
  href?: string;
  cta?: string; // inline link label on /feed; falls back to "Read more"
  showInHomeArticleWidget?: boolean;
};

const baseAnnouncements: Announcement[] = [
  {
    date: '2026-08-28',
    kind: 'update',
    headline: 'A bigger video library, and one that reads Chinese.',
    body: 'The library is up to 61 hand-picked videos, ordered best first instead of by the date they were added, and it now opens in Chinese at its own address. Every entry has been checked against YouTube, so nothing on the shelf is a dead link.',
    href: '/videos',
    cta: 'Browse the library',
  },
  {
    date: '2026-08-27',
    kind: 'release',
    headline: 'Set up any position, then share it.',
    body: 'A board editor for eight variants: place pieces by hand, set the side to move, and hand the position straight to the analysis board. The analysis board also takes a FEN directly, and every position you build has its own link.',
    href: '/editor/xiangqi',
    cta: 'Open the editor',
  },
  {
    date: '2026-08-27',
    kind: 'release',
    headline: 'A head-to-head record on every finished game.',
    body: 'The review page gains a Crosstable with your record against that opponent in that variant, engines included, and Share and export hands you the game as PGN or JSON.',
    href: '/games',
    cta: 'Find a game',
  },
  {
    date: '2026-08-27',
    kind: 'update',
    headline: 'Chess titles count for verification now.',
    body: 'GM, IM, FM and the rest join the xiangqi titles. A verified title puts a badge beside your name wherever people are listed, and opens a coaching page students can find. Verification takes about two minutes.',
    href: '/blog/titled-players',
    cta: 'Read the article',
  },
  {
    date: '2026-08-27',
    kind: 'update',
    headline: 'Board coordinates, on every board that has them.',
    body: 'One switch in Display settings reaches the xiangqi family, the chess boards, jungle, and shogi. Xiangqi counts its files from each player’s own right, so the labels follow your move-notation setting and change sides when you flip the board.',
    href: '/account/settings/display',
    cta: 'Open settings',
  },
  {
    date: '2026-08-27',
    kind: 'update',
    headline: 'Follow a forum thread without refreshing it.',
    body: 'Watch a topic and the bell counts its unread replies. Quoting someone now tells them, and every source the bell reports has its own switch.',
    href: '/forum',
    cta: 'Join the forum',
  },
  {
    date: '2026-08-26',
    kind: 'release',
    headline: 'Studies read and write PGN.',
    body: 'Import a PGN to build a study, export one chapter or all of them, and add a finished game to a study from its link. The opening explorer sits beside the board while you work.',
    href: '/study',
    cta: 'Browse the studies',
  },
  {
    date: '2026-08-23',
    kind: 'article',
    headline: 'The Riverbank Cannon Problem.',
    body: 'Red’s opening cannon reaches the riverbank first, one move from firing down any of five files, and in fog you never see it coming. Whether that breaks the game came down to one elephant move, one poisoned defense, and a coin flip we priced with the engine.',
    href: '/blog/riverbank-cannon',
    cta: 'Read the article',
  },
  {
    date: '2026-08-23',
    kind: 'update',
    headline: 'Puzzles are rated by how hard they play.',
    body: 'A puzzle’s rating used to come from how many moves the mate took, which says little about how hard it is to find. It now comes from the position itself, so what you are served sits closer to your rating.',
    href: '/puzzles',
    cta: 'Solve puzzles',
  },
  {
    date: '2026-08-23',
    kind: 'update',
    headline: 'Pick a flair for your name.',
    body: 'Choose a small icon that shows beside your handle across the site, from the variant markers and xiangqi characters the boards already use. The bell also reports new followers and incoming challenges now.',
    href: '/account',
    cta: 'Edit your profile',
  },
  {
    date: '2026-08-22',
    kind: 'update',
    headline: 'Both house bots play stronger.',
    body: 'Misty runs version 1.6 in fog chess, which closes a queen hang it used to walk into. Pikafish now searches jieqi to full depth; it had been stopping early, which made it easier to beat than it should have been.',
    href: '/',
    cta: 'Find a game',
  },
  {
    date: '2026-08-22',
    kind: 'update',
    headline: 'Four times as many xiangqi puzzles.',
    body: 'The standard xiangqi set goes from 394 puzzles to 1,605, every one mined from a finished game and checked by the engine before it ships.',
    href: '/puzzles',
    cta: 'Solve puzzles',
  },
  {
    date: '2026-08-22',
    kind: 'release',
    headline: 'Move badges and best lines on every reviewable variant.',
    body: 'The move-judgment badge now sits on the board for all six variants with analysis, not xiangqi alone, and a blunder names the move that refutes it. Jieqi reveal plies get the ranked candidates the engine scored instead of a line, since nothing past a flip is knowable.',
    href: '/analysis',
    cta: 'Open the board',
  },
  {
    date: '2026-08-22',
    kind: 'article',
    headline: 'Separating skill from luck in flip games.',
    body: 'Half the moves in banqi, jieqi, and flip jungle are dice rolls, so a chess-style review blames you for variance. Game review splits every flip into the decision you made and the tile you got, and the article runs that over 52 human-versus-engine games.',
    href: '/blog/skill-vs-luck',
    cta: 'Read the article',
  },
  {
    date: '2026-08-13',
    kind: 'update',
    headline: 'What Patron support will cost.',
    body: 'The Support page lists the monthly amounts, what they include (a profile badge, no gameplay advantage), and the billing and refund terms in full. Checkout is not open yet.',
    href: '/patron',
    cta: 'See the amounts',
    showInHomeArticleWidget: false,
  },
  {
    date: '2026-08-13',
    kind: 'release',
    headline: 'A games database for xiangqi.',
    body: 'Search finished games from three sources in one place: the historical corpus, the tournament boards we broadcast, and games played here.',
    href: '/games',
    cta: 'Search the games',
  },
  {
    date: '2026-08-13',
    kind: 'release',
    headline: 'Perpetual check now loses in standard xiangqi.',
    body: 'Repeating a check forever used to draw. The checker has to vary or lose the game, which is how the published rulesets score it and how the course has always taught it.',
    href: '/rules/xiangqi',
    cta: 'Study the rules',
  },
  {
    date: '2026-08-08',
    kind: 'release',
    headline: 'Mistboard works on a phone.',
    body: 'Every page was swept at phone width: a full-size live board, lobby rows that still name the variant, and real touch targets on the controls you tap.',
    href: '/',
    cta: 'Find a game',
  },
  {
    date: '2026-08-08',
    kind: 'update',
    headline: 'Every composition has its own page.',
    body: 'Each endgame composition in the library is a page you can link to, and sharing one previews its own diagram rather than the site card.',
    href: '/study',
    cta: 'Browse the studies',
  },
  {
    date: '2026-08-03',
    kind: 'release',
    headline: 'Mistboard reads in Chinese.',
    body: 'Playing, watching, the forum, and the xiangqi rules pages are all available in Simplified and Traditional Chinese. Switch languages in the settings menu.',
    href: '/rules/xiangqi',
    cta: 'Study the rules',
    showInHomeArticleWidget: false,
  },
  {
    date: '2026-07-28',
    kind: 'release',
    headline: 'Rated games at every time control.',
    body: 'Bullet, blitz, and rapid each keep their own rating now, instead of rated meaning 3+2 only. Correspondence stays casual on purpose.',
    href: '/leaderboard',
    cta: 'See the leaderboard',
    showInHomeArticleWidget: false,
  },
  {
    date: '2026-07-23',
    kind: 'release',
    headline: 'An opening explorer for xiangqi.',
    body: 'Open any position on the analysis board and see what has been played from it, with example games to study and the corpus it came from named on the panel.',
    href: '/analysis',
    cta: 'Open the board',
  },
  {
    date: '2026-07-22',
    kind: 'release',
    headline: 'Rated xiangqi is live.',
    body: 'Choose Rated in the lobby. Your rating starts at 1500 and appears after it settles.',
    href: '/leaderboard',
    cta: 'See the leaderboard',
    showInHomeArticleWidget: false,
  },
  {
    date: '2026-07-23',
    kind: 'article',
    headline: 'Secret in the Tangerine, both game volumes.',
    body: 'Both volumes are playable move by move in English: 33 games with every printed variation.',
    href: '/study/Dfi3NpRE',
    cta: 'Open volume one',
    showInHomeArticleWidget: false,
  },
  {
    date: '2026-07-21',
    kind: 'article',
    headline: 'Classical xiangqi, from the original woodblocks.',
    body: 'Read the earliest printings move by move, with every corrected misprint marked on the board.',
    href: '/study',
    cta: 'Browse the studies',
    showInHomeArticleWidget: false,
  },
  {
    date: '2026-07-17',
    kind: 'release',
    headline: 'Correspondence play has launched.',
    body: 'Post or accept a days-per-move seek, or send a friend a challenge link and play at your own pace.',
    href: '/',
    cta: 'Find a game',
  },
  {
    date: '2026-07-17',
    kind: 'release',
    headline: 'An analysis board for every game.',
    body: 'Set up any position, import moves, run a local evaluation, or grade a finished game with server analysis.',
    href: '/analysis',
    cta: 'Open the board',
  },
  {
    date: '2026-07-11',
    kind: 'release',
    headline: 'Studies have launched.',
    body: 'Build shareable analysis boards: draw on the board, comment, branch variations, organize chapters, and publish interactive gamebook lessons.',
    href: '/study',
    cta: 'Browse studies',
  },
  {
    date: '2026-07-11',
    kind: 'release',
    headline: 'Mistboard TV is live.',
    body: 'Watch live games on the new Watch page, with a channel for every game and an Engines channel for bot-versus-bot matches.',
    href: '/watch',
    cta: 'Watch now',
  },
  {
    date: '2026-07-10',
    kind: 'release',
    headline: 'Learn xiangqi from scratch.',
    body: 'A free interactive course: 20 stages and 111 hands-on levels take you from how each piece moves to the named checkmate patterns.',
    href: '/learn',
    cta: 'Start the course',
  },
  {
    date: '2026-07-10',
    kind: 'release',
    headline: 'Xiangqi puzzles have launched.',
    body: 'Tactics mined from real games, with puzzle ratings, hints, and a daily puzzle on the homepage.',
    href: '/puzzles',
    cta: 'Solve puzzles',
  },
  {
    date: '2026-07-04',
    kind: 'release',
    headline: 'Xiangqi has launched.',
    body: 'Standard Chinese chess on the full 9 by 10 board is now first-class on Mistboard: play the Pikafish engine at three strengths, or challenge a friend.',
    href: '/rules/xiangqi',
    cta: 'Study the rules',
  },
  {
    date: '2026-07-03',
    kind: 'release',
    headline: 'Forum and global chat have launched.',
    body: 'The forum is open for game analysis, engine talk, and site feedback, with the homepage global chat available for quick table-talk during live sessions.',
    href: '/forum',
    cta: 'Join the forum',
  },
  {
    date: '2026-07-01',
    kind: 'release',
    headline: 'Fortress has launched.',
    body: 'Xiangqi with a pocket: every piece moves as in Chinese chess, plus crazyhouse-style drops and the new Treasure. Play the bot or challenge a friend.',
    href: '/rules/fortress-xiangqi',
    cta: 'Study the rules',
  },
  {
    date: '2026-06-30',
    kind: 'release',
    headline: 'Jungle Chess has launched.',
    body: 'Rank-based animal chess on a 7 by 9 board with rivers, dens, and traps is live. Challenge a friend or take on the Misty Jungle engine.',
    href: '/rules/jungle',
    cta: 'Read rules',
  },
  {
    date: '2026-06-30',
    kind: 'release',
    headline: 'Flip Jungle has launched.',
    body: 'Every animal starts face-down on a 4 by 4 board and flips as you play. Challenge a friend or the engine.',
    href: '/rules/jungle-flip',
    cta: 'Read rules',
  },
  {
    date: '2026-06-22',
    kind: 'release',
    headline: 'Drop Mini Xiangqi has launched.',
    body: 'The 7 by 7 reserve fight is live with no enemy-palace drops, a full rules page, and a 114-ply FSF sample game to study.',
    href: '/rules/drop-mini-xiangqi',
    cta: 'Study the rules',
  },
  {
    date: '2026-06-20',
    kind: 'release',
    headline: 'Dark Crazyhouse has launched.',
    body: 'Crazyhouse under Fog of War is now live for invite games, with private hands, captured pieces entering reserve, and drops into the fog.',
    href: '/rules/dark-crazyhouse',
    cta: 'Read rules',
  },
  {
    date: '2026-06-20',
    kind: 'release',
    headline: 'Dark Crossroads Chess has launched.',
    body: 'Crossroads Chess under Fog of War is now live for invite games, with hidden enemy pieces, no check warnings, and the far-rank Try.',
    href: '/rules/dark-crossroads-chess',
    cta: 'Read rules',
  },
  {
    date: '2026-06-20',
    kind: 'release',
    headline: 'Fog Shogi has launched.',
    body: 'Shogi under Fog of War is now live for invite games, with private hands, drops into the fog, and king capture wins.',
    href: '/rules/dark-shogi',
    cta: 'Read rules',
  },
  {
    date: '2026-06-20',
    kind: 'release',
    headline: 'Kriegspiel is open for alpha play.',
    body: 'The original hidden-information chess: see only your own pieces, try moves through the umpire, and challenge a friend to a match.',
    href: '/rules/kriegspiel',
    cta: 'Read rules',
    showInHomeArticleWidget: false,
  },
  {
    date: '2026-06-18',
    kind: 'release',
    headline: 'Reveal Chess is open for alpha play.',
    body: 'Standard chess with a hidden starting arrangement: every piece but the king begins face-down and reveals its true identity the moment it moves. Challenge a friend to a match.',
    href: '/rules/reveal-chess',
    cta: 'Read rules',
  },
  {
    date: '2026-06-18',
    kind: 'release',
    headline: 'Fog Xiangqi is open for alpha play.',
    body: 'Fog of War on the full 9 by 10 xiangqi board: each side sees only the points its pieces reach. Challenge a friend to a match.',
    href: '/rules/fog-xiangqi',
    cta: 'Read rules',
  },
  {
    date: '2026-06-17',
    kind: 'release',
    headline: 'Banqi is open for alpha play.',
    body: 'Banqi on an 8 by 4 board: all 32 pieces start face-down and flip as you play. Challenge a friend to a match.',
    href: '/rules/banqi',
    cta: 'Read rules',
    showInHomeArticleWidget: false,
  },
  {
    date: '2026-06-15',
    kind: 'release',
    headline: 'Jieqi is open for alpha play.',
    body: 'Hidden-identity xiangqi: every non-general piece starts face-down and reveals as it moves. Take on PikaJieQi, our jieqi engine.',
    href: '/rules/jieqi',
    cta: 'Read rules',
  },
  {
    date: '2026-06-11',
    kind: 'release',
    headline: 'Crossroads Chess has launched.',
    body: 'A 6 by 8 chess-xiangqi variant with checkmate and king-race wins is now live on Mistboard.',
    href: '/rules/crossroads-chess',
    cta: 'Read rules',
  },
  {
    date: '2026-05-09',
    kind: 'release',
    headline: 'Fog Chess is open for alpha play.',
    body: 'Fog of War chess is live on Mistboard, with private vision, no check warnings, and king capture wins.',
    href: '/rules/fog-chess',
    cta: 'Read rules',
  },
  {
    date: '2026-05-09',
    kind: 'status',
    headline: 'Mistboard is in alpha.',
    body: 'Casual dark chess is open. Rated beta is coming.',
    href: '/contact',
    cta: 'Send feedback',
  },
  {
    date: '2026-06-09',
    kind: 'release',
    headline: 'Dark Mini Xiangqi is open for alpha play.',
    body: 'A smaller Fog of War variant on a 7 by 7 xiangqi board, with Misty engine support.',
    href: '/rules/dark-mini-xiangqi',
    cta: 'Read rules',
  },
  {
    date: '2026-06-03',
    kind: 'release',
    headline: 'Misty 1.0 has launched.',
    body: 'Our Fog of War dark chess engine is now live to play.',
    href: '/?play=computer',
    cta: 'Play the engine',
  },
];

export function announcements(): Announcement[] {
  return baseAnnouncements;
}
