// GENERATED by docs-private/luck-article/gen-figures.ts from the mined exhibit
// game bq_7e8ce2e7-8e64-4453-b9fd-9dcc4bd52fa9 (sweep + decision-vs-luck decomposition at analysis
// budget). Do not hand-edit; re-run the generator (see docs-private/luck-article/FINDINGS.md).

import type { BanqiDeal } from '@mistboard/game';

// The exhibit game from the article: brianhliou (Black) beats MistyBanqi (Red)
// over 156 plies, carried by +76 points of flip luck. Live game:
// /banqi/game/bq_7e8ce2e7-8e64-4453-b9fd-9dcc4bd52fa9
export const BANQI_LUCK_GAME: { deal: BanqiDeal; moves: string } = {
  // The 32-tile deal in ALL_BANQI_SQUARES order (a1, b1, ... h1, a2, ... h4).
  deal: [
    { color: 'black', role: 'elephant' },
    { color: 'black', role: 'general' },
    { color: 'red', role: 'chariot' },
    { color: 'red', role: 'chariot' },
    { color: 'black', role: 'soldier' },
    { color: 'black', role: 'chariot' },
    { color: 'red', role: 'soldier' },
    { color: 'red', role: 'horse' },
    { color: 'black', role: 'cannon' },
    { color: 'red', role: 'horse' },
    { color: 'black', role: 'cannon' },
    { color: 'red', role: 'advisor' },
    { color: 'red', role: 'soldier' },
    { color: 'red', role: 'soldier' },
    { color: 'red', role: 'general' },
    { color: 'red', role: 'cannon' },
    { color: 'black', role: 'advisor' },
    { color: 'black', role: 'soldier' },
    { color: 'red', role: 'elephant' },
    { color: 'red', role: 'soldier' },
    { color: 'red', role: 'cannon' },
    { color: 'black', role: 'advisor' },
    { color: 'black', role: 'soldier' },
    { color: 'black', role: 'chariot' },
    { color: 'red', role: 'elephant' },
    { color: 'black', role: 'elephant' },
    { color: 'black', role: 'soldier' },
    { color: 'black', role: 'horse' },
    { color: 'black', role: 'horse' },
    { color: 'black', role: 'soldier' },
    { color: 'red', role: 'advisor' },
    { color: 'red', role: 'soldier' },
  ] as BanqiDeal,
  // Space-separated from+to tokens; a flip is the self-move from==to.
  moves:
    'b2b2 g2g2 h1h1 f2f2 a1a1 g3g3 g4g4 g3g2 f2g2 e3e3 h3h3 d1d1 e3h3 c3c3 d3d3 h2h2 e2e2 g1g1 d4d4 f1f1 h3g3 f1g1 g3g1 e1e1 g1f1 e1e2 h2e2 d2d2 c4c4 f3f3 c3c4 f3f2 f1g1 f2g2 g1f1 g2f2 g4g3 f2f1 c4d4 f1f2 d3c3 a2a2 e2e3 a4a4 b2a2 a1a2 d1e1 b3b3 c3b3 a2b2 b3c3 b2b3 e3b3 b1b1 c1c1 b1b2 h4h4 b2b1 c1d1 b1c1 g3f3 f2f3 b3f3 c1d1 e1f1 d1d2 c3d3 d2e2 d3e3 e2f2 e3e2 f2f3 h4h3 c2c2 d4d3 c2c1 f1g1 a3a3 h1h2 a3a4 h3g3 a4a3 d3c3 a3b3 c3c2 c1d1 g1f1 b3c3 f1e1 c3c2 e1d1 c2d2 d1c1 d2e2 g3f3 e2e3 f3g3 b4b4 c1c2 b4b3 g3h3 e3d3 c2c1 b3b2 c1d1 d3d2 d1e1 b2c2 e1f1 c2c1 f1f2 c1d1 f2f3 d2e2 f4f4 d1e1 f3f4 e1f1 h3h4 f1g1 e4e4 e4e3 h4g4 e3d3 f4e4 g1g2 h2h3 e2e3 e4d4 d3d2 g4f4 d2e2 h3h4 e2f2 f4e4 g2g3 e4f4 f2f3 f4e4 f3f4 d4c4 f4e4 c4c3 e3d3 c3b3 d3c3 b3b2 e4d4 b2a2 c3b3 a2a1 b3b2 h4g4 g3g4 a1b1 b2b1',
};

// Every tile the ply-6 flip at g3 could have been (27 face-down tiles,
// 12 kinds), each with the mover's win% if that tile were under the square,
// evaluated at decision budget with the fixed-multiset donor swap. Weighted mean
// 44.9, reproducing the shipped decomposition's playedWin 44.9.
export const BANQI_LUCK_FLIP_POOL: {
  square: string;
  total: number;
  mean: number;
  rows: Array<{ color: string; role: string; count: number; win: number; actual: boolean }>;
} = {
  square: 'g3',
  total: 27,
  mean: 44.9,
  rows: [
    { color: 'black', role: 'soldier', count: 5, win: 82.1, actual: true },
    { color: 'red', role: 'soldier', count: 4, win: 46.4, actual: false },
    { color: 'red', role: 'chariot', count: 2, win: 45.1, actual: false },
    { color: 'red', role: 'elephant', count: 2, win: 44.2, actual: false },
    { color: 'red', role: 'advisor', count: 2, win: 42.5, actual: false },
    { color: 'red', role: 'cannon', count: 2, win: 41.1, actual: false },
    { color: 'black', role: 'horse', count: 2, win: 33.8, actual: false },
    { color: 'black', role: 'chariot', count: 2, win: 31.3, actual: false },
    { color: 'black', role: 'elephant', count: 1, win: 28.9, actual: false },
    { color: 'black', role: 'advisor', count: 2, win: 25.4, actual: false },
    { color: 'black', role: 'cannon', count: 2, win: 23.2, actual: false },
    { color: 'black', role: 'general', count: 1, win: 13.3, actual: false },
  ],
};
